# Generated by Django 3.2.8 on 2022-06-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(auto_created=True, blank=True, max_length=255, null=True)),
                ('chat_id', models.IntegerField(auto_created=True, blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='-', max_length=255, null=True, verbose_name='Nomi')),
                ('price', models.PositiveBigIntegerField(default=0, null=True, verbose_name='Narxi')),
                ('brand', models.TextField(choices=[('Samsung', 'Samsung'), ('Lg', 'Lg'), ('Shivaki', 'Shivaki'), ('Artel', 'Artel')], max_length=255, verbose_name='Brend')),
                ('count', models.PositiveIntegerField(default=0, null=True, verbose_name='Qolgan')),
            ],
        ),
    ]
